Update workflows

diff --git a/.github/workflows/detect-secrets.yml b/.github/workflows/detect-secrets.yml
--- a/.github/workflows/detect-secrets.yml
+++ b/.github/workflows/detect-secrets.yml
@@ -1,8 +1,7 @@
-name: Detect-secrets
+name: Detect-secrets analysis
 
 on:
   push:
-    branches: [ main, develop ]
   pull_request:
     branches: [ main, develop ]
 
@@ -17,25 +16,42 @@ jobs:
         uses: actions/setup-python@v2
         with:
           python-version: 3.7
+
       - name: Install detect-secrets
         run: |
           python -m pip install --upgrade pip
-          python -m pip install detect-secrets==1.0.3
+          python -m pip install detect-secrets==1.1.0
+
       - name: Find secrets
+        id: secrets
         run: |
           detect-secrets -v scan --baseline .secrets.baseline
           detect-secrets audit --json --stats .secrets.baseline > secrets_stats.json
           UNKNOWN_SECRETS_COUNT=$(cat secrets_stats.json | jq .[].stats.raw.unknown | paste -sd+ - | bc -l)
           REAL_SECRETS_COUNT=$(cat secrets_stats.json | jq .[].stats.raw.\"true-positives\" | paste -sd+ - | bc -l)
           if [[ $UNKNOWN_SECRETS_COUNT -gt 0 ]]; then
-            echo "Detected new secrets in source code"
-            exit 1
+            echo "::error Detected new secrets in source code"
           fi
           if [[ $REAL_SECRETS_COUNT -gt 0 ]]; then
-            echo "Detected secrets without fix in source code"
-            exit 2
+            echo "::warning Detected secrets without fix in source code"
           fi
+
+          echo "::set-output name=unknown-secrets::$UNKNOWN_SECRETS_COUNT"
+          echo "::set-output name=real-secrets::$REAL_SECRETS_COUNT"
+
+      - name: Upload baseline
+        uses: actions/upload-artifact@v2
+        if: ${{ steps.secrets.outputs.unknown-secrets }} > 0
+        with:
+          name: Secrets references
+          path: .secrets.baseline
+          if-no-files-found: ignore
+          retention-days: 7
           
       - name: Remove files
         run: rm -f secrets_stats.json
+      
+      - name: Exit
+        if: ${{ steps.secrets.outputs.unknown-secrets }} > 0
+        run: exit 1
 
